### ISSUE TITLE
listhomes error

### ISSUE THREAD

**Issue by Dhenier** [LapisPlugins/HomeSpawn#4]
Paper 65 - 1.14.2
HomeSpawn 3.1.3

Please see error report:
https://pastebin.com/9FYpEBdd

Thanks for the fast response on the forums, but I tested it and it still has the same issue.

**Comment by Dart2112** [comment]
[HomeSpawn.zip](https://github.com/LapisPlugins/HomeSpawn/files/3294006/HomeSpawn.zip)
Try that version. That error should be impossible so Paper must mess with the spec for offline players

**Comment by HppyDedPxl** [comment]
Error persists with the zipped version, without Paper.
https://pastebin.com/k5jZg7Zc 
Hope this helps.

Other active plugins
LuckPerms-Bukkit 4.4.1
EssentialsX 2.16.1.169

**Comment by Dart2112** [comment]
Unfortunately, that's not possible without something in your server being broken. The server is giving my plugin a null OfflinePlayer which is what causes the error, either that or it's not giving a username. either way what's happening is something weird with your profile or server.

**Comment by maxspeed3006** [comment]
Getting the same issue, maybe it's because my server has the parameter online-mode=false?

**Comment by HppyDedPxl** [comment]
Alright, seeing people still have this issue, I fixed the bug for me. I attached the jar but I wouldn't advise people to just randomly download a jar from the internet and put it on their server.

[HomeSpawn.zip](https://github.com/LapisPlugins/HomeSpawn/files/3333124/HomeSpawn.zip)
Disclaimer: "it works on my machine, might not on yours, untested in any other environment."

So, while I didn't do an in depth review of your code, I did notice two pecularities, that people, if they want to fix it themselves might wanna look into.

a) When cloning your project, maven could not resolve all dependencies for me (This might be on me though.). Am I correct in the assumption that org.mineacademy is a paid library that you are using? 
Because of that, compiling the jar was not possible. So I removed everything to do with this, since it only seemed to provide UI code that I didn't need.

b) When using homelist on an online player you use getOfflinePlayer(uuid). Admittedly, I have never worked with the Bukkit API, but to my knowledge there is 1. getPlayer(uuid) for this case, because getOfflinePlayer is essentially just an extension that covering offline players by polling the mojang servers, which can't happen if the online player is issuing the command unless an admin tries to get the homelist for an offline player, which could be handled seperately, and 2. getOfflinePlayer has been deprecated since a few Bukkit API versions already. So it might be worth investigating this and updating the plugin to the new Bukkit API version.

In any case, b is not necessary for the fix, removing minecademy and all code routes that led to it has fixed the error, which again, is weird because according to my  server set up, those routes should not have been taken in the first place.

Finally, thank you Benjamin for your hard work and the nice Plugin you wrote, it makes the minecraft experience for my players and me much more enjoyable, so please don't take this as smart assery or an insult, it is not. Especially not since I didn't invest enough time into this to have an educated opinion on your work here.

**Comment by Dart2112** [comment]
> Alright, seeing people still have this issue, I fixed the bug for me. I attached the jar but I wouldn't advise people to just randomly download a jar from the internet and put it on their server.
> 
> [HomeSpawn.zip](https://github.com/LapisPlugins/HomeSpawn/files/3333124/HomeSpawn.zip)
> Disclaimer: "it works on my machine, might not on yours, untested in any other environment."
> 
> So, while I didn't do an in depth review of your code, I did notice two pecularities, that people, if they want to fix it themselves might wanna look into.
> 
> a) When cloning your project, maven could not resolve all dependencies for me (This might be on me though.). Am I correct in the assumption that org.mineacademy is a paid library that you are using?
> Because of that, compiling the jar was not possible. So I removed everything to do with this, since it only seemed to provide UI code that I didn't need.
> 
> b) When using homelist on an online player you use getOfflinePlayer(uuid). Admittedly, I have never worked with the Bukkit API, but to my knowledge there is 1. getPlayer(uuid) for this case, because getOfflinePlayer is essentially just an extension that covering offline players by polling the mojang servers, which can't happen if the online player is issuing the command unless an admin tries to get the homelist for an offline player, which could be handled seperately, and 2. getOfflinePlayer has been deprecated since a few Bukkit API versions already. So it might be worth investigating this and updating the plugin to the new Bukkit API version.
> 
> In any case, b is not necessary for the fix, removing minecademy and all code routes that led to it has fixed the error, which again, is weird because according to my server set up, those routes should not have been taken in the first place.
> 
> Finally, thank you Benjamin for your hard work and the nice Plugin you wrote, it makes the minecraft experience for my players and me much more enjoyable, so please don't take this as smart assery or an insult, it is not. Especially not since I didn't invest enough time into this to have an educated opinion on your work here.

a) it's not paid but it also isn't hosted in a maven repo so I clone it down from GitHub and install it in my local repo, in this plugin it does only provide the home's list GUI and the material setup for cross-version compatibility. Which is no longer required if the GUI code is removed.

b) The reason I use an offline player is that I need the UUID of the player and I need the code to work for online and offline players when I only have the players name. The code is incorrectly depreciated because I am using a player name and not the UUID which is impossible to get without using an offline player(see discussion [HERE](https://www.spigotmc.org/threads/deprecation-server-getofflineplayer-string-name.117862/) pay particular attention the last paragraph in the OP). Because of this, there is no way of "updating the plugin to the new Bukkit API version" since no alternative way to get a UUID from a player name has been provided in the API. In this case, the fact that the player is online makes no difference other than the fact that the server can use the information it has loaded about the player so it doesn't have to ping the Mojang servers. Offline player objects are routinely used in spigot plugins as a way to use the same method for both online and offline players, although the name makes it sound like the offline player should only be used for *offline* players, that isn't the case. 

The error only occurs in the GUI which is why it doesn't happen when you remove all of the GUI code. Although it works its a kind of brute force way to fix the error. Simply disabling the GUI in the config should also fix the error without editing the jar file.

**Comment by TheNety** [comment]
Hello, I am having the same problem.
Using Paper for 1.13.2 and HomeSpawn version 3.1.3
https://pastebin.com/A85XECGL

**Comment by Dart2112** [comment]
Alright, I might have finally got it but I can't reproduce the error so attached is the **hopefully** fixed jar
[Homespawn.zip](https://github.com/LapisPlugins/HomeSpawn/files/3373027/Homespawn.zip)

**Comment by Dart2112** [comment]
One last ditch effort to fix this error
[Homespawn.zip](https://github.com/LapisPlugins/HomeSpawn/files/3377109/Homespawn.zip)

**Comment by Dart2112** [comment]
Confirmed fixed by vitrium on Spigot
