### ISSUE TITLE
Server Lag if you use "/homeslist" the first time after Server restart

### ISSUE THREAD

**Issue by T0biii** [LapisPlugins/HomeSpawn#8]
Server Lag if you use "/homeslist" the first time you use it after Server start

```
 [Server thread/INFO]: T0biii issued server command: /homelist
 [Server thread/WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
```

```
[INFO]: This server is running Paper version git-Paper-416 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
[INFO]: Checking version, please wait...
[INFO]: Previous version: git-Paper-414 (MC: 1.16.4)
[INFO]: You are running the latest version
```

**Comment by Dart2112** [comment]
Working on making it async, update to follow soon

**Comment by T0biii** [comment]
Why dont Drop Legacy Material Support?
I think that is the Reason why the Server lags because he needs to load the Materials? or am I wrong?

**Comment by Dart2112** [comment]
Update pushed to the auto-updater and posting on spigot now. There is a new message in the messages.yml file so it will regen it

The legacy material support is because I am using XMaterial to allow materials from different versions to be used such that the plugin will work on many different Minecraft versions. The lag is caused by the UI doing a heap of maths and grabbing data from the homes. This should only happen the first time the GUI is loaded and only on servers that are less powerful
